Update community.json
monome/norns-community pull request #152
Opened 2021-09-14 21:09 UTC by kevinlindley

Added the delinquencer and demoncore scripts

2021-09-14 21:12 UTC, kevinlindley commented
Am I doing something wrong ?

2021-09-14 21:43 UTC, ngwese requested changes

2021-09-14 21:43 UTC, ngwese commented on community.json
> +    },
This line needs to be followed by an open curly brace `{` for the next script

2021-09-14 21:45 UTC, ngwese commented
If you are stuck let me know an I can fix it manually.

2021-09-15 18:07 UTC, closed without merging

2021-09-15 18:11 UTC, kevinlindley commented
Hi Greg,

Made the change but just can't seem to get the hang of GitHub's workflow. Using GitHub exceeds my patience threshold. :-)

Kind Regards
Kevin.


> On 14 September 2021 at 22:45 Greg Wuller ***@***.***> wrote:
> 
> 
>     If you are stuck let me know an I can fix it manually.
> 
>     —
>     You are receiving this because you authored the thread.
>     Reply to this email directly, view it on GitHub https://github.com/monome/norns-community/pull/152#issuecomment-919535110 , or unsubscribe https://github.com/notifications/unsubscribe-auth/AICTQSSIFLJW732RZIOWFDDUB667JANCNFSM5EBAGDDQ .
>     Triage notifications on the go with GitHub Mobile for iOS https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675 or Android https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub .
>

2021-09-15 19:44 UTC, ngwese commented
so sorry to have dropped the ball on this. i got lost i my own projects in the evening and forgot to follow through on this. i’ll fix it up and push it through.

2021-09-15 19:58 UTC, ngwese commented
okay you should be good to go now
https://github.com/monome/norns-community/commit/2a4090ff9c6bfd08b38b8ebb9599d487d420c622

again sorry for the bumps

2021-09-15 20:13 UTC, kevinlindley commented
Thank you, problem at my end.

Kind Regards
Kevin


> On 15 September 2021 at 20:59 Greg Wuller ***@***.***> wrote:
> 
> 
>     okay you should be good to go now
>     2a4090f https://github.com/monome/norns-community/commit/2a4090ff9c6bfd08b38b8ebb9599d487d420c622
> 
>     again sorry for the bumps
> 
>     —
>     You are receiving this because you modified the open/close state.
>     Reply to this email directly, view it on GitHub https://github.com/monome/norns-community/pull/152#issuecomment-920333995 , or unsubscribe https://github.com/notifications/unsubscribe-auth/AICTQSWJGPAGY6OUFWIKVTLUCD3IVANCNFSM5EBAGDDQ .
>     Triage notifications on the go with GitHub Mobile for iOS https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675 or Android https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub .
>